// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
import { inter } from '@/app/ui/fonts';
// import { Provider } from "./Providers";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (

//     <html lang="en">
//             <body className={`${inter.className} antialiased`}><Provider>{children}</Provider></body>

//     </html>
//   );
// }

import "./globals.css";
import { Providers } from "./Providers";

export const metadata = {
  title: "Collab AI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="/logo32x32.png"
          rel="icon"
          sizes="32x32"
          type="image/png"
        />
        <link
          href="/logo16x16.png"
          rel="icon"
          sizes="16x16"
          type="image/png"
        />
      </head>
      <body className={`${inter.className} antialiased`}>
                <Providers>{children}</Providers>
      </body>
    </html>
  );
}